# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import beget_openapi_cloud
from beget_openapi_cloud.paths.v1_cloud_projects_list import get  # noqa: E501
from beget_openapi_cloud import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV1CloudProjectsList(ApiTestMixin, unittest.TestCase):
    """
    V1CloudProjectsList unit test stubs
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
