# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.4.2
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_cloud
from beget_openapi_cloud.model.mysql_statistic_get_memory_response import MysqlStatisticGetMemoryResponse
from beget_openapi_cloud import configuration


class TestMysqlStatisticGetMemoryResponse(unittest.TestCase):
    """MysqlStatisticGetMemoryResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
