# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_cloud
from beget_openapi_cloud.model.cdn_settings_response_headers_hiding_policy import CdnSettingsResponseHeadersHidingPolicy
from beget_openapi_cloud import configuration


class TestCdnSettingsResponseHeadersHidingPolicy(unittest.TestCase):
    """CdnSettingsResponseHeadersHidingPolicy unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
