# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_cloud
from beget_openapi_cloud.model.project_create_project_response import ProjectCreateProjectResponse
from beget_openapi_cloud import configuration


class TestProjectCreateProjectResponse(unittest.TestCase):
    """ProjectCreateProjectResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
