# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.3.1
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_cloud
from beget_openapi_cloud.model.postgresql_pg_get_db_list_response import PostgresqlPgGetDbListResponse
from beget_openapi_cloud import configuration


class TestPostgresqlPgGetDbListResponse(unittest.TestCase):
    """PostgresqlPgGetDbListResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
