# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.7
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_cloud
from beget_openapi_cloud.model.cdn_cdn_create_params_source_params import CdnCdnCreateParamsSourceParams
from beget_openapi_cloud import configuration


class TestCdnCdnCreateParamsSourceParams(unittest.TestCase):
    """CdnCdnCreateParamsSourceParams unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
