# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_cloud
from beget_openapi_cloud.model.mysql_mysql5 import MysqlMysql5
from beget_openapi_cloud import configuration


class TestMysqlMysql5(unittest.TestCase):
    """MysqlMysql5 unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
