# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.2.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_cloud
from beget_openapi_cloud.model.mysql_remove_db_response_error import MysqlRemoveDbResponseError
from beget_openapi_cloud import configuration


class TestMysqlRemoveDbResponseError(unittest.TestCase):
    """MysqlRemoveDbResponseError unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
