# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.5.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_cloud
from beget_openapi_cloud.model.s3_change_access_key_response import S3ChangeAccessKeyResponse
from beget_openapi_cloud import configuration


class TestS3ChangeAccessKeyResponse(unittest.TestCase):
    """S3ChangeAccessKeyResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
