# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.4.1
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_cloud
from beget_openapi_cloud.model.postgresql_pg_set_config_request import PostgresqlPgSetConfigRequest
from beget_openapi_cloud import configuration


class TestPostgresqlPgSetConfigRequest(unittest.TestCase):
    """PostgresqlPgSetConfigRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
