# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.4.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_cloud
from beget_openapi_cloud.model.s3_change_domain_response_error import S3ChangeDomainResponseError
from beget_openapi_cloud import configuration


class TestS3ChangeDomainResponseError(unittest.TestCase):
    """S3ChangeDomainResponseError unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
