# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from beget_openapi_cloud.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    V1_CLOUD = "/v1/cloud"
    V1_CLOUD_CONFIGURATION = "/v1/cloud/configuration"
    V1_CLOUD_MYSQL_BACKUP = "/v1/cloud/mysql/backup"
    V1_CLOUD_MYSQL_BACKUP_ORDERS = "/v1/cloud/mysql/backup/orders"
    V1_CLOUD_MYSQL_BACKUP_COPY_ID = "/v1/cloud/mysql/backup/{copy_id}"
    V1_CLOUD_MYSQL_SERVICE_ID_CONFIG = "/v1/cloud/mysql/{service_id}/config"
    V1_CLOUD_MYSQL_SERVICE_ID_DB = "/v1/cloud/mysql/{service_id}/db"
    V1_CLOUD_MYSQL_SERVICE_ID_DB_DB_NAME = "/v1/cloud/mysql/{service_id}/db/{db_name}"
    V1_CLOUD_MYSQL_SERVICE_ID_DB_DB_NAME_ACCESS = "/v1/cloud/mysql/{service_id}/db/{db_name}/access"
    V1_CLOUD_MYSQL_SERVICE_ID_DB_DB_NAME_ACCESS_HOST = "/v1/cloud/mysql/{service_id}/db/{db_name}/access/{host}"
    V1_CLOUD_MYSQL_SERVICE_ID_STATISTIC_CPU = "/v1/cloud/mysql/{service_id}/statistic/cpu"
    V1_CLOUD_MYSQL_SERVICE_ID_STATISTIC_CPUDETAILS = "/v1/cloud/mysql/{service_id}/statistic/cpu-details"
    V1_CLOUD_MYSQL_SERVICE_ID_STATISTIC_DISK = "/v1/cloud/mysql/{service_id}/statistic/disk"
    V1_CLOUD_MYSQL_SERVICE_ID_STATISTIC_DISKUSAGE = "/v1/cloud/mysql/{service_id}/statistic/disk-usage"
    V1_CLOUD_MYSQL_SERVICE_ID_STATISTIC_LOADAVERAGE = "/v1/cloud/mysql/{service_id}/statistic/load-average"
    V1_CLOUD_MYSQL_SERVICE_ID_STATISTIC_MEMORY = "/v1/cloud/mysql/{service_id}/statistic/memory"
    V1_CLOUD_MYSQL_SERVICE_ID_STATISTIC_NETWORK = "/v1/cloud/mysql/{service_id}/statistic/network"
    V1_CLOUD_POSTGRESQL_BACKUP = "/v1/cloud/postgresql/backup"
    V1_CLOUD_POSTGRESQL_BACKUP_ORDERS = "/v1/cloud/postgresql/backup/orders"
    V1_CLOUD_POSTGRESQL_BACKUP_COPY_ID = "/v1/cloud/postgresql/backup/{copy_id}"
    V1_CLOUD_POSTGRESQL_SERVICE_ID_CONFIG = "/v1/cloud/postgresql/{service_id}/config"
    V1_CLOUD_POSTGRESQL_SERVICE_ID_DB = "/v1/cloud/postgresql/{service_id}/db"
    V1_CLOUD_POSTGRESQL_SERVICE_ID_DB_DB_NAME = "/v1/cloud/postgresql/{service_id}/db/{db_name}"
    V1_CLOUD_POSTGRESQL_SERVICE_ID_REMOTEACCESS = "/v1/cloud/postgresql/{service_id}/remote-access"
    V1_CLOUD_POSTGRESQL_SERVICE_ID_ROLE = "/v1/cloud/postgresql/{service_id}/role"
    V1_CLOUD_POSTGRESQL_SERVICE_ID_ROLE_ROLE_NAME = "/v1/cloud/postgresql/{service_id}/role/{role_name}"
    V1_CLOUD_POSTGRESQL_SERVICE_ID_STATISTIC_CPU = "/v1/cloud/postgresql/{service_id}/statistic/cpu"
    V1_CLOUD_POSTGRESQL_SERVICE_ID_STATISTIC_CPUDETAILS = "/v1/cloud/postgresql/{service_id}/statistic/cpu-details"
    V1_CLOUD_POSTGRESQL_SERVICE_ID_STATISTIC_DISK = "/v1/cloud/postgresql/{service_id}/statistic/disk"
    V1_CLOUD_POSTGRESQL_SERVICE_ID_STATISTIC_DISKUSAGE = "/v1/cloud/postgresql/{service_id}/statistic/disk-usage"
    V1_CLOUD_POSTGRESQL_SERVICE_ID_STATISTIC_LOADAVERAGE = "/v1/cloud/postgresql/{service_id}/statistic/load-average"
    V1_CLOUD_POSTGRESQL_SERVICE_ID_STATISTIC_MEMORY = "/v1/cloud/postgresql/{service_id}/statistic/memory"
    V1_CLOUD_POSTGRESQL_SERVICE_ID_STATISTIC_NETWORK = "/v1/cloud/postgresql/{service_id}/statistic/network"
    V1_CLOUD_S3_PREFIX = "/v1/cloud/s3/prefix"
    V1_CLOUD_S3_PRICE = "/v1/cloud/s3/price"
    V1_CLOUD_S3_QUOTA = "/v1/cloud/s3/quota"
    V1_CLOUD_S3_SERVICE_ID_ACCESSKEY = "/v1/cloud/s3/{service_id}/access-key"
    V1_CLOUD_S3_SERVICE_ID_CORS = "/v1/cloud/s3/{service_id}/cors"
    V1_CLOUD_S3_SERVICE_ID_DOMAIN = "/v1/cloud/s3/{service_id}/domain"
    V1_CLOUD_S3_SERVICE_ID_PUBLIC = "/v1/cloud/s3/{service_id}/public"
    V1_CLOUD_SERVICE_ID = "/v1/cloud/{service_id}"
    V1_CLOUD_SERVICE_ID_CONFIGURATION = "/v1/cloud/{service_id}/configuration"
