# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Generated by: https://openapi-generator.tech
"""

from beget_openapi_cloud.paths.v1_cloud_cdn_service_id_statistic_network.get import CdnStatisticServiceGetNetwork
from beget_openapi_cloud.paths.v1_cloud_cdn_service_id_statistic_count_request.get import CdnStatisticServiceGetRequest
from beget_openapi_cloud.paths.v1_cloud_cdn_service_id_statistic_traffic_usage.get import CdnStatisticServiceGetTraffic


class CdnStatisticServiceApi(
    CdnStatisticServiceGetNetwork,
    CdnStatisticServiceGetRequest,
    CdnStatisticServiceGetTraffic,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
