# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.5.0
    Generated by: https://openapi-generator.tech
"""

from beget_openapi_cloud.paths.v1_cloud_cdn_service_id_resource_domains.post import CdnServiceChangeResourceDomains
from beget_openapi_cloud.paths.v1_cloud_cdn_service_id_setting.post import CdnServiceChangeSetting
from beget_openapi_cloud.paths.v1_cloud_cdn_price.get import CdnServiceGetPrice
from beget_openapi_cloud.paths.v1_cloud_cdn_source_domains.get import CdnServiceGetSourceDomains
from beget_openapi_cloud.paths.v1_cloud_cdn_service_id_preload_cache_by_paths.post import CdnServicePreloadCacheByPaths
from beget_openapi_cloud.paths.v1_cloud_cdn_service_id_purge_all_cache.get import CdnServicePurgeAllCache
from beget_openapi_cloud.paths.v1_cloud_cdn_service_id_purge_cache_by_paths.post import CdnServicePurgeCacheByPaths


class CdnServiceApi(
    CdnServiceChangeResourceDomains,
    CdnServiceChangeSetting,
    CdnServiceGetPrice,
    CdnServiceGetSourceDomains,
    CdnServicePreloadCacheByPaths,
    CdnServicePurgeAllCache,
    CdnServicePurgeCacheByPaths,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
