# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.4.0
    Generated by: https://openapi-generator.tech
"""

from beget_openapi_cloud.paths.v1_cloud_service_id_configuration.patch import CloudServiceChangeConfiguration
from beget_openapi_cloud.paths.v1_cloud.post import CloudServiceCreate
from beget_openapi_cloud.paths.v1_cloud_service_id.get import CloudServiceGet
from beget_openapi_cloud.paths.v1_cloud_configuration.get import CloudServiceGetConfigurationList
from beget_openapi_cloud.paths.v1_cloud.get import CloudServiceGetList
from beget_openapi_cloud.paths.v1_cloud_service_id.delete import CloudServiceRemove
from beget_openapi_cloud.paths.v1_cloud_service_id.patch import CloudServiceUpdate


class CloudServiceApi(
    CloudServiceChangeConfiguration,
    CloudServiceCreate,
    CloudServiceGet,
    CloudServiceGetConfigurationList,
    CloudServiceGetList,
    CloudServiceRemove,
    CloudServiceUpdate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
