# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Generated by: https://openapi-generator.tech
"""

from beget_openapi_cloud.paths.v1_cloud_mysql_service_id_statistic_cpu.get import MysqlStatisticServiceGetCpu
from beget_openapi_cloud.paths.v1_cloud_mysql_service_id_statistic_cpu_details.get import MysqlStatisticServiceGetCpuDetails
from beget_openapi_cloud.paths.v1_cloud_mysql_service_id_statistic_disk.get import MysqlStatisticServiceGetDisk
from beget_openapi_cloud.paths.v1_cloud_mysql_service_id_statistic_disk_usage.get import MysqlStatisticServiceGetDiskUsage
from beget_openapi_cloud.paths.v1_cloud_mysql_service_id_statistic_load_average.get import MysqlStatisticServiceGetLoadAverage
from beget_openapi_cloud.paths.v1_cloud_mysql_service_id_statistic_memory.get import MysqlStatisticServiceGetMemory
from beget_openapi_cloud.paths.v1_cloud_mysql_service_id_statistic_network.get import MysqlStatisticServiceGetNetwork


class MysqlStatisticServiceApi(
    MysqlStatisticServiceGetCpu,
    MysqlStatisticServiceGetCpuDetails,
    MysqlStatisticServiceGetDisk,
    MysqlStatisticServiceGetDiskUsage,
    MysqlStatisticServiceGetLoadAverage,
    MysqlStatisticServiceGetMemory,
    MysqlStatisticServiceGetNetwork,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
