# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.4.1
    Generated by: https://openapi-generator.tech
"""

from beget_openapi_cloud.paths.v1_cloud_mysql_backup.get import MysqlBackupServiceGetList
from beget_openapi_cloud.paths.v1_cloud_mysql_backup_orders.get import MysqlBackupServiceGetOrders
from beget_openapi_cloud.paths.v1_cloud_mysql_backup_copy_id.post import MysqlBackupServiceRestore


class MysqlBackupServiceApi(
    MysqlBackupServiceGetList,
    MysqlBackupServiceGetOrders,
    MysqlBackupServiceRestore,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
