# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.4.2
    Generated by: https://openapi-generator.tech
"""

from beget_openapi_cloud.paths.v1_cloud_postgresql_service_id_db.post import PostgresqlServiceCreateDb
from beget_openapi_cloud.paths.v1_cloud_postgresql_service_id_role.post import PostgresqlServiceCreateRole
from beget_openapi_cloud.paths.v1_cloud_postgresql_service_id_config.get import PostgresqlServiceGetConfig
from beget_openapi_cloud.paths.v1_cloud_postgresql_service_id_db.get import PostgresqlServiceGetDbList
from beget_openapi_cloud.paths.v1_cloud_postgresql_service_id_remote_access.get import PostgresqlServiceGetRemoteAccess
from beget_openapi_cloud.paths.v1_cloud_postgresql_service_id_role.get import PostgresqlServiceGetRoleList
from beget_openapi_cloud.paths.v1_cloud_postgresql_service_id_db_db_name.delete import PostgresqlServiceRemoveDb
from beget_openapi_cloud.paths.v1_cloud_postgresql_service_id_role_role_name.delete import PostgresqlServiceRemoveRole
from beget_openapi_cloud.paths.v1_cloud_postgresql_service_id_config.put import PostgresqlServiceSetConfig
from beget_openapi_cloud.paths.v1_cloud_postgresql_service_id_db_db_name.patch import PostgresqlServiceUpdateDb
from beget_openapi_cloud.paths.v1_cloud_postgresql_service_id_remote_access.put import PostgresqlServiceUpdateRemoteAccess
from beget_openapi_cloud.paths.v1_cloud_postgresql_service_id_role_role_name.patch import PostgresqlServiceUpdateRole


class PostgresqlServiceApi(
    PostgresqlServiceCreateDb,
    PostgresqlServiceCreateRole,
    PostgresqlServiceGetConfig,
    PostgresqlServiceGetDbList,
    PostgresqlServiceGetRemoteAccess,
    PostgresqlServiceGetRoleList,
    PostgresqlServiceRemoveDb,
    PostgresqlServiceRemoveRole,
    PostgresqlServiceSetConfig,
    PostgresqlServiceUpdateDb,
    PostgresqlServiceUpdateRemoteAccess,
    PostgresqlServiceUpdateRole,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
