# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.5.0
    Generated by: https://openapi-generator.tech
"""

from beget_openapi_cloud.paths.v1_cloud_postgresql_service_id_statistic_cpu.get import PostgresqlStatisticServiceGetCpu
from beget_openapi_cloud.paths.v1_cloud_postgresql_service_id_statistic_cpu_details.get import PostgresqlStatisticServiceGetCpuDetails
from beget_openapi_cloud.paths.v1_cloud_postgresql_service_id_statistic_disk.get import PostgresqlStatisticServiceGetDisk
from beget_openapi_cloud.paths.v1_cloud_postgresql_service_id_statistic_disk_usage.get import PostgresqlStatisticServiceGetDiskUsage
from beget_openapi_cloud.paths.v1_cloud_postgresql_service_id_statistic_load_average.get import PostgresqlStatisticServiceGetLoadAverage
from beget_openapi_cloud.paths.v1_cloud_postgresql_service_id_statistic_memory.get import PostgresqlStatisticServiceGetMemory
from beget_openapi_cloud.paths.v1_cloud_postgresql_service_id_statistic_network.get import PostgresqlStatisticServiceGetNetwork


class PostgresqlStatisticServiceApi(
    PostgresqlStatisticServiceGetCpu,
    PostgresqlStatisticServiceGetCpuDetails,
    PostgresqlStatisticServiceGetDisk,
    PostgresqlStatisticServiceGetDiskUsage,
    PostgresqlStatisticServiceGetLoadAverage,
    PostgresqlStatisticServiceGetMemory,
    PostgresqlStatisticServiceGetNetwork,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
