# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.5.0
    Generated by: https://openapi-generator.tech
"""

from beget_openapi_cloud.paths.v1_cloud_postgresql_backup.get import PostgresqlBackupServiceGetList
from beget_openapi_cloud.paths.v1_cloud_postgresql_backup_orders.get import PostgresqlBackupServiceGetOrders
from beget_openapi_cloud.paths.v1_cloud_postgresql_backup_copy_id.post import PostgresqlBackupServiceRestore


class PostgresqlBackupServiceApi(
    PostgresqlBackupServiceGetList,
    PostgresqlBackupServiceGetOrders,
    PostgresqlBackupServiceRestore,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
