# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Generated by: https://openapi-generator.tech
"""

from beget_openapi_cloud.paths.v1_cloud_projects.post import ProjectServiceCreate
from beget_openapi_cloud.paths.v1_cloud_projects_list.get import ProjectServiceGetList
from beget_openapi_cloud.paths.v1_cloud_projects_project_id.delete import ProjectServiceRemove
from beget_openapi_cloud.paths.v1_cloud_projects_project_id.put import ProjectServiceUpdate


class ProjectServiceApi(
    ProjectServiceCreate,
    ProjectServiceGetList,
    ProjectServiceRemove,
    ProjectServiceUpdate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
