# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Generated by: https://openapi-generator.tech
"""

from beget_openapi_cloud.paths.v1_cloud_s3_service_id_statistic_network.get import S3StatisticServiceGetNetwork
from beget_openapi_cloud.paths.v1_cloud_s3_service_id_statistic_quota.get import S3StatisticServiceGetQuota
from beget_openapi_cloud.paths.v1_cloud_s3_service_id_statistic_count_request.get import S3StatisticServiceGetRequest
from beget_openapi_cloud.paths.v1_cloud_s3_service_id_statistic_traffic_usage.get import S3StatisticServiceGetTraffic


class S3StatisticServiceApi(
    S3StatisticServiceGetNetwork,
    S3StatisticServiceGetQuota,
    S3StatisticServiceGetRequest,
    S3StatisticServiceGetTraffic,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
