# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.5.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_cloud import schemas  # noqa: F401


class CdnCdnCreateError(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def error() -> typing.Type['CdnCdnCreateErrorError']:
                return CdnCdnCreateErrorError
            
            
            class domain_error(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['CdnCdnCreateErrorDomainError']:
                        return CdnCdnCreateErrorDomainError
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['CdnCdnCreateErrorDomainError'], typing.List['CdnCdnCreateErrorDomainError']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'domain_error':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'CdnCdnCreateErrorDomainError':
                    return super().__getitem__(i)
            __annotations__ = {
                "error": error,
                "domain_error": domain_error,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["error"]) -> 'CdnCdnCreateErrorError': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["domain_error"]) -> MetaOapg.properties.domain_error: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["error", "domain_error", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["error"]) -> typing.Union['CdnCdnCreateErrorError', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["domain_error"]) -> typing.Union[MetaOapg.properties.domain_error, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["error", "domain_error", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        error: typing.Union['CdnCdnCreateErrorError', schemas.Unset] = schemas.unset,
        domain_error: typing.Union[MetaOapg.properties.domain_error, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CdnCdnCreateError':
        return super().__new__(
            cls,
            *args,
            error=error,
            domain_error=domain_error,
            _configuration=_configuration,
            **kwargs,
        )

from beget_openapi_cloud.model.cdn_cdn_create_error_domain_error import CdnCdnCreateErrorDomainError
from beget_openapi_cloud.model.cdn_cdn_create_error_error import CdnCdnCreateErrorError
