# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_cloud import schemas  # noqa: F401


class CdnGetPriceResponse(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            
            
            class cdn(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['CdnGetPriceResponseCdn']:
                        return CdnGetPriceResponseCdn
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['CdnGetPriceResponseCdn'], typing.List['CdnGetPriceResponseCdn']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'cdn':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'CdnGetPriceResponseCdn':
                    return super().__getitem__(i)
            required_topup_amount = schemas.Float64Schema
            __annotations__ = {
                "cdn": cdn,
                "required_topup_amount": required_topup_amount,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cdn"]) -> MetaOapg.properties.cdn: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["required_topup_amount"]) -> MetaOapg.properties.required_topup_amount: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["cdn", "required_topup_amount", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cdn"]) -> typing.Union[MetaOapg.properties.cdn, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["required_topup_amount"]) -> typing.Union[MetaOapg.properties.required_topup_amount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["cdn", "required_topup_amount", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        cdn: typing.Union[MetaOapg.properties.cdn, list, tuple, schemas.Unset] = schemas.unset,
        required_topup_amount: typing.Union[MetaOapg.properties.required_topup_amount, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CdnGetPriceResponse':
        return super().__new__(
            cls,
            *args,
            cdn=cdn,
            required_topup_amount=required_topup_amount,
            _configuration=_configuration,
            **kwargs,
        )

from beget_openapi_cloud.model.cdn_get_price_response_cdn import CdnGetPriceResponseCdn
