# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.5.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_cloud import schemas  # noqa: F401


class CdnGetPriceResponseCdn(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            cdn_service_id = schemas.StrSchema
            display_name = schemas.StrSchema
            created_at = schemas.StrSchema
            traffic_amount = schemas.IntSchema
            traffic_rate = schemas.Float64Schema
            __annotations__ = {
                "cdn_service_id": cdn_service_id,
                "display_name": display_name,
                "created_at": created_at,
                "traffic_amount": traffic_amount,
                "traffic_rate": traffic_rate,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cdn_service_id"]) -> MetaOapg.properties.cdn_service_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["display_name"]) -> MetaOapg.properties.display_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["created_at"]) -> MetaOapg.properties.created_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["traffic_amount"]) -> MetaOapg.properties.traffic_amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["traffic_rate"]) -> MetaOapg.properties.traffic_rate: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["cdn_service_id", "display_name", "created_at", "traffic_amount", "traffic_rate", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cdn_service_id"]) -> typing.Union[MetaOapg.properties.cdn_service_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["display_name"]) -> typing.Union[MetaOapg.properties.display_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["created_at"]) -> typing.Union[MetaOapg.properties.created_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["traffic_amount"]) -> typing.Union[MetaOapg.properties.traffic_amount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["traffic_rate"]) -> typing.Union[MetaOapg.properties.traffic_rate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["cdn_service_id", "display_name", "created_at", "traffic_amount", "traffic_rate", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        cdn_service_id: typing.Union[MetaOapg.properties.cdn_service_id, str, schemas.Unset] = schemas.unset,
        display_name: typing.Union[MetaOapg.properties.display_name, str, schemas.Unset] = schemas.unset,
        created_at: typing.Union[MetaOapg.properties.created_at, str, schemas.Unset] = schemas.unset,
        traffic_amount: typing.Union[MetaOapg.properties.traffic_amount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        traffic_rate: typing.Union[MetaOapg.properties.traffic_rate, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CdnGetPriceResponseCdn':
        return super().__new__(
            cls,
            *args,
            cdn_service_id=cdn_service_id,
            display_name=display_name,
            created_at=created_at,
            traffic_amount=traffic_amount,
            traffic_rate=traffic_rate,
            _configuration=_configuration,
            **kwargs,
        )
