# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_cloud import schemas  # noqa: F401


class CdnChangeResourceDomainsResponseError(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            
            
            class code(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def _(cls):
                    return cls("_")
                
                @schemas.classproperty
                def INTERNAL_ERROR(cls):
                    return cls("INTERNAL_ERROR")
                
                @schemas.classproperty
                def DOMAIN_NOT_REGISTERED(cls):
                    return cls("DOMAIN_NOT_REGISTERED")
                
                @schemas.classproperty
                def DOMAIN_INCORRECT_NS(cls):
                    return cls("DOMAIN_INCORRECT_NS")
                
                @schemas.classproperty
                def NOT_SUBDOMAIN(cls):
                    return cls("NOT_SUBDOMAIN")
                
                @schemas.classproperty
                def DOMAIN_NOT_FOUND(cls):
                    return cls("DOMAIN_NOT_FOUND")
                
                @schemas.classproperty
                def DOMAIN_ALREADY_USED(cls):
                    return cls("DOMAIN_ALREADY_USED")
                
                @schemas.classproperty
                def DOMAIN_INVALID(cls):
                    return cls("DOMAIN_INVALID")
            message = schemas.StrSchema
            items = schemas.StrSchema
        
            @staticmethod
            def domain_already_used_details() -> typing.Type['CdnChangeResourceDomainsResponseErrorDomainAlreadyUsedDetails']:
                return CdnChangeResourceDomainsResponseErrorDomainAlreadyUsedDetails
            __annotations__ = {
                "code": code,
                "message": message,
                "items": items,
                "domain_already_used_details": domain_already_used_details,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["code"]) -> MetaOapg.properties.code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["message"]) -> MetaOapg.properties.message: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["items"]) -> MetaOapg.properties.items: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["domain_already_used_details"]) -> 'CdnChangeResourceDomainsResponseErrorDomainAlreadyUsedDetails': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["code", "message", "items", "domain_already_used_details", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["code"]) -> typing.Union[MetaOapg.properties.code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["message"]) -> typing.Union[MetaOapg.properties.message, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["items"]) -> typing.Union[MetaOapg.properties.items, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["domain_already_used_details"]) -> typing.Union['CdnChangeResourceDomainsResponseErrorDomainAlreadyUsedDetails', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["code", "message", "items", "domain_already_used_details", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        code: typing.Union[MetaOapg.properties.code, str, schemas.Unset] = schemas.unset,
        message: typing.Union[MetaOapg.properties.message, str, schemas.Unset] = schemas.unset,
        items: typing.Union[MetaOapg.properties.items, str, schemas.Unset] = schemas.unset,
        domain_already_used_details: typing.Union['CdnChangeResourceDomainsResponseErrorDomainAlreadyUsedDetails', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CdnChangeResourceDomainsResponseError':
        return super().__new__(
            cls,
            *args,
            code=code,
            message=message,
            items=items,
            domain_already_used_details=domain_already_used_details,
            _configuration=_configuration,
            **kwargs,
        )

from beget_openapi_cloud.model.cdn_change_resource_domains_response_error_domain_already_used_details import CdnChangeResourceDomainsResponseErrorDomainAlreadyUsedDetails
