# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.3
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_cloud import schemas  # noqa: F401


class CdnChangeResourceDomainsResponse(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def resource_domain() -> typing.Type['CdnChangeResourceDomainsResponseResourceDomains']:
                return CdnChangeResourceDomainsResponseResourceDomains
        
            @staticmethod
            def domain_errors() -> typing.Type['CdnChangeResourceDomainsResponseDomainErrors']:
                return CdnChangeResourceDomainsResponseDomainErrors
        
            @staticmethod
            def error() -> typing.Type['CdnChangeResourceDomainsResponseError']:
                return CdnChangeResourceDomainsResponseError
            __annotations__ = {
                "resource_domain": resource_domain,
                "domain_errors": domain_errors,
                "error": error,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["resource_domain"]) -> 'CdnChangeResourceDomainsResponseResourceDomains': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["domain_errors"]) -> 'CdnChangeResourceDomainsResponseDomainErrors': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["error"]) -> 'CdnChangeResourceDomainsResponseError': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["resource_domain", "domain_errors", "error", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["resource_domain"]) -> typing.Union['CdnChangeResourceDomainsResponseResourceDomains', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["domain_errors"]) -> typing.Union['CdnChangeResourceDomainsResponseDomainErrors', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["error"]) -> typing.Union['CdnChangeResourceDomainsResponseError', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["resource_domain", "domain_errors", "error", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        resource_domain: typing.Union['CdnChangeResourceDomainsResponseResourceDomains', schemas.Unset] = schemas.unset,
        domain_errors: typing.Union['CdnChangeResourceDomainsResponseDomainErrors', schemas.Unset] = schemas.unset,
        error: typing.Union['CdnChangeResourceDomainsResponseError', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CdnChangeResourceDomainsResponse':
        return super().__new__(
            cls,
            *_args,
            resource_domain=resource_domain,
            domain_errors=domain_errors,
            error=error,
            _configuration=_configuration,
            **kwargs,
        )

from beget_openapi_cloud.model.cdn_change_resource_domains_response_domain_errors import CdnChangeResourceDomainsResponseDomainErrors
from beget_openapi_cloud.model.cdn_change_resource_domains_response_error import CdnChangeResourceDomainsResponseError
from beget_openapi_cloud.model.cdn_change_resource_domains_response_resource_domains import CdnChangeResourceDomainsResponseResourceDomains
