# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.5.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_cloud import schemas  # noqa: F401


class CdnSettingsStale(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            enable = schemas.BoolSchema
            
            
            class type(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    
                    class items(
                        schemas.EnumBase,
                        schemas.StrSchema
                    ):
                    
                    
                        class MetaOapg:
                            format = 'enum'
                            enum_value_to_name = {
                                "HTTP_403": "HTTP_403",
                                "HTTP_404": "HTTP_404",
                                "HTTP_429": "HTTP_429",
                                "HTTP_500": "HTTP_500",
                                "HTTP_502": "HTTP_502",
                                "HTTP_503": "HTTP_503",
                                "HTTP_504": "HTTP_504",
                                "INVALID_HEADER": "INVALID_HEADER",
                                "TIMEOUT": "TIMEOUT",
                                "CACHE_UPDATING": "CACHE_UPDATING",
                            }
                        
                        @schemas.classproperty
                        def HTTP_403(cls):
                            return cls("HTTP_403")
                        
                        @schemas.classproperty
                        def HTTP_404(cls):
                            return cls("HTTP_404")
                        
                        @schemas.classproperty
                        def HTTP_429(cls):
                            return cls("HTTP_429")
                        
                        @schemas.classproperty
                        def HTTP_500(cls):
                            return cls("HTTP_500")
                        
                        @schemas.classproperty
                        def HTTP_502(cls):
                            return cls("HTTP_502")
                        
                        @schemas.classproperty
                        def HTTP_503(cls):
                            return cls("HTTP_503")
                        
                        @schemas.classproperty
                        def HTTP_504(cls):
                            return cls("HTTP_504")
                        
                        @schemas.classproperty
                        def INVALID_HEADER(cls):
                            return cls("INVALID_HEADER")
                        
                        @schemas.classproperty
                        def TIMEOUT(cls):
                            return cls("TIMEOUT")
                        
                        @schemas.classproperty
                        def CACHE_UPDATING(cls):
                            return cls("CACHE_UPDATING")
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'type':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            __annotations__ = {
                "enable": enable,
                "type": type,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["enable"]) -> MetaOapg.properties.enable: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["enable", "type", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["enable"]) -> typing.Union[MetaOapg.properties.enable, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> typing.Union[MetaOapg.properties.type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["enable", "type", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        enable: typing.Union[MetaOapg.properties.enable, bool, schemas.Unset] = schemas.unset,
        type: typing.Union[MetaOapg.properties.type, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CdnSettingsStale':
        return super().__new__(
            cls,
            *args,
            enable=enable,
            type=type,
            _configuration=_configuration,
            **kwargs,
        )
