# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.5.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_cloud import schemas  # noqa: F401


class CdnStatisticGetRequestResponse(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def code_2xx() -> typing.Type['StructuresStatisticSeriesData']:
                return StructuresStatisticSeriesData
        
            @staticmethod
            def code_3xx() -> typing.Type['StructuresStatisticSeriesData']:
                return StructuresStatisticSeriesData
        
            @staticmethod
            def code_4xx() -> typing.Type['StructuresStatisticSeriesData']:
                return StructuresStatisticSeriesData
        
            @staticmethod
            def code_5xx() -> typing.Type['StructuresStatisticSeriesData']:
                return StructuresStatisticSeriesData
            __annotations__ = {
                "code_2xx": code_2xx,
                "code_3xx": code_3xx,
                "code_4xx": code_4xx,
                "code_5xx": code_5xx,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["code_2xx"]) -> 'StructuresStatisticSeriesData': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["code_3xx"]) -> 'StructuresStatisticSeriesData': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["code_4xx"]) -> 'StructuresStatisticSeriesData': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["code_5xx"]) -> 'StructuresStatisticSeriesData': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["code_2xx", "code_3xx", "code_4xx", "code_5xx", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["code_2xx"]) -> typing.Union['StructuresStatisticSeriesData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["code_3xx"]) -> typing.Union['StructuresStatisticSeriesData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["code_4xx"]) -> typing.Union['StructuresStatisticSeriesData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["code_5xx"]) -> typing.Union['StructuresStatisticSeriesData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["code_2xx", "code_3xx", "code_4xx", "code_5xx", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        code_2xx: typing.Union['StructuresStatisticSeriesData', schemas.Unset] = schemas.unset,
        code_3xx: typing.Union['StructuresStatisticSeriesData', schemas.Unset] = schemas.unset,
        code_4xx: typing.Union['StructuresStatisticSeriesData', schemas.Unset] = schemas.unset,
        code_5xx: typing.Union['StructuresStatisticSeriesData', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CdnStatisticGetRequestResponse':
        return super().__new__(
            cls,
            *args,
            code_2xx=code_2xx,
            code_3xx=code_3xx,
            code_4xx=code_4xx,
            code_5xx=code_5xx,
            _configuration=_configuration,
            **kwargs,
        )

from beget_openapi_cloud.model.structures_statistic_series_data import StructuresStatisticSeriesData
