# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.5.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_cloud import schemas  # noqa: F401


class CdnCdn(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            
            
            class resource_domain(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['CdnResourceDomain']:
                        return CdnResourceDomain
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['CdnResourceDomain'], typing.List['CdnResourceDomain']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'resource_domain':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'CdnResourceDomain':
                    return super().__getitem__(i)
        
            @staticmethod
            def source_domain() -> typing.Type['CdnSourceDomain']:
                return CdnSourceDomain
        
            @staticmethod
            def settings() -> typing.Type['CdnSettings']:
                return CdnSettings
            __annotations__ = {
                "resource_domain": resource_domain,
                "source_domain": source_domain,
                "settings": settings,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["resource_domain"]) -> MetaOapg.properties.resource_domain: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["source_domain"]) -> 'CdnSourceDomain': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["settings"]) -> 'CdnSettings': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["resource_domain", "source_domain", "settings", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["resource_domain"]) -> typing.Union[MetaOapg.properties.resource_domain, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["source_domain"]) -> typing.Union['CdnSourceDomain', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["settings"]) -> typing.Union['CdnSettings', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["resource_domain", "source_domain", "settings", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        resource_domain: typing.Union[MetaOapg.properties.resource_domain, list, tuple, schemas.Unset] = schemas.unset,
        source_domain: typing.Union['CdnSourceDomain', schemas.Unset] = schemas.unset,
        settings: typing.Union['CdnSettings', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CdnCdn':
        return super().__new__(
            cls,
            *args,
            resource_domain=resource_domain,
            source_domain=source_domain,
            settings=settings,
            _configuration=_configuration,
            **kwargs,
        )

from beget_openapi_cloud.model.cdn_resource_domain import CdnResourceDomain
from beget_openapi_cloud.model.cdn_settings import CdnSettings
from beget_openapi_cloud.model.cdn_source_domain import CdnSourceDomain
