# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_cloud import schemas  # noqa: F401


class CdnSourceDomain(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            cdn_service_id = schemas.StrSchema
            source_service_id = schemas.StrSchema
            
            
            class source_service_type(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def DOMAIN(cls):
                    return cls("DOMAIN")
                
                @schemas.classproperty
                def S3(cls):
                    return cls("S3")
                
                @schemas.classproperty
                def VPS(cls):
                    return cls("VPS")
            items = schemas.StrSchema
            source_service_display_name = schemas.StrSchema
            source_service_slug = schemas.StrSchema
            __annotations__ = {
                "cdn_service_id": cdn_service_id,
                "source_service_id": source_service_id,
                "source_service_type": source_service_type,
                "items": items,
                "source_service_display_name": source_service_display_name,
                "source_service_slug": source_service_slug,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cdn_service_id"]) -> MetaOapg.properties.cdn_service_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["source_service_id"]) -> MetaOapg.properties.source_service_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["source_service_type"]) -> MetaOapg.properties.source_service_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["items"]) -> MetaOapg.properties.items: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["source_service_display_name"]) -> MetaOapg.properties.source_service_display_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["source_service_slug"]) -> MetaOapg.properties.source_service_slug: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["cdn_service_id", "source_service_id", "source_service_type", "items", "source_service_display_name", "source_service_slug", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cdn_service_id"]) -> typing.Union[MetaOapg.properties.cdn_service_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["source_service_id"]) -> typing.Union[MetaOapg.properties.source_service_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["source_service_type"]) -> typing.Union[MetaOapg.properties.source_service_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["items"]) -> typing.Union[MetaOapg.properties.items, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["source_service_display_name"]) -> typing.Union[MetaOapg.properties.source_service_display_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["source_service_slug"]) -> typing.Union[MetaOapg.properties.source_service_slug, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["cdn_service_id", "source_service_id", "source_service_type", "items", "source_service_display_name", "source_service_slug", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        cdn_service_id: typing.Union[MetaOapg.properties.cdn_service_id, str, schemas.Unset] = schemas.unset,
        source_service_id: typing.Union[MetaOapg.properties.source_service_id, str, schemas.Unset] = schemas.unset,
        source_service_type: typing.Union[MetaOapg.properties.source_service_type, str, schemas.Unset] = schemas.unset,
        items: typing.Union[MetaOapg.properties.items, str, schemas.Unset] = schemas.unset,
        source_service_display_name: typing.Union[MetaOapg.properties.source_service_display_name, str, schemas.Unset] = schemas.unset,
        source_service_slug: typing.Union[MetaOapg.properties.source_service_slug, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CdnSourceDomain':
        return super().__new__(
            cls,
            *args,
            cdn_service_id=cdn_service_id,
            source_service_id=source_service_id,
            source_service_type=source_service_type,
            items=items,
            source_service_display_name=source_service_display_name,
            source_service_slug=source_service_slug,
            _configuration=_configuration,
            **kwargs,
        )
