# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.4.2
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_cloud import schemas  # noqa: F401


class PostgresqlBackupRestoreRequest(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            copy_id = schemas.StrSchema
            service_uuid = schemas.StrSchema
            __annotations__ = {
                "copy_id": copy_id,
                "service_uuid": service_uuid,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["copy_id"]) -> MetaOapg.properties.copy_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["service_uuid"]) -> MetaOapg.properties.service_uuid: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["copy_id", "service_uuid", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["copy_id"]) -> typing.Union[MetaOapg.properties.copy_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["service_uuid"]) -> typing.Union[MetaOapg.properties.service_uuid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["copy_id", "service_uuid", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        copy_id: typing.Union[MetaOapg.properties.copy_id, str, schemas.Unset] = schemas.unset,
        service_uuid: typing.Union[MetaOapg.properties.service_uuid, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PostgresqlBackupRestoreRequest':
        return super().__new__(
            cls,
            *args,
            copy_id=copy_id,
            service_uuid=service_uuid,
            _configuration=_configuration,
            **kwargs,
        )
