# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.4.1
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_cloud import schemas  # noqa: F401


class S3GetPriceResponse(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            rate_day = schemas.Float64Schema
            rate_day_overload = schemas.Float64Schema
            __annotations__ = {
                "rate_day": rate_day,
                "rate_day_overload": rate_day_overload,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rate_day"]) -> MetaOapg.properties.rate_day: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rate_day_overload"]) -> MetaOapg.properties.rate_day_overload: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["rate_day", "rate_day_overload", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rate_day"]) -> typing.Union[MetaOapg.properties.rate_day, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rate_day_overload"]) -> typing.Union[MetaOapg.properties.rate_day_overload, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["rate_day", "rate_day_overload", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        rate_day: typing.Union[MetaOapg.properties.rate_day, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        rate_day_overload: typing.Union[MetaOapg.properties.rate_day_overload, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'S3GetPriceResponse':
        return super().__new__(
            cls,
            *args,
            rate_day=rate_day,
            rate_day_overload=rate_day_overload,
            _configuration=_configuration,
            **kwargs,
        )
