# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.5.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_cloud import schemas  # noqa: F401


class S3StatisticGetRequestResponse(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def method_get() -> typing.Type['StructuresStatisticSeriesData']:
                return StructuresStatisticSeriesData
        
            @staticmethod
            def method_post() -> typing.Type['StructuresStatisticSeriesData']:
                return StructuresStatisticSeriesData
        
            @staticmethod
            def method_put() -> typing.Type['StructuresStatisticSeriesData']:
                return StructuresStatisticSeriesData
        
            @staticmethod
            def method_head() -> typing.Type['StructuresStatisticSeriesData']:
                return StructuresStatisticSeriesData
        
            @staticmethod
            def method_delete() -> typing.Type['StructuresStatisticSeriesData']:
                return StructuresStatisticSeriesData
        
            @staticmethod
            def method_options() -> typing.Type['StructuresStatisticSeriesData']:
                return StructuresStatisticSeriesData
            __annotations__ = {
                "method_get": method_get,
                "method_post": method_post,
                "method_put": method_put,
                "method_head": method_head,
                "method_delete": method_delete,
                "method_options": method_options,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["method_get"]) -> 'StructuresStatisticSeriesData': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["method_post"]) -> 'StructuresStatisticSeriesData': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["method_put"]) -> 'StructuresStatisticSeriesData': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["method_head"]) -> 'StructuresStatisticSeriesData': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["method_delete"]) -> 'StructuresStatisticSeriesData': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["method_options"]) -> 'StructuresStatisticSeriesData': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["method_get", "method_post", "method_put", "method_head", "method_delete", "method_options", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["method_get"]) -> typing.Union['StructuresStatisticSeriesData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["method_post"]) -> typing.Union['StructuresStatisticSeriesData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["method_put"]) -> typing.Union['StructuresStatisticSeriesData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["method_head"]) -> typing.Union['StructuresStatisticSeriesData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["method_delete"]) -> typing.Union['StructuresStatisticSeriesData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["method_options"]) -> typing.Union['StructuresStatisticSeriesData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["method_get", "method_post", "method_put", "method_head", "method_delete", "method_options", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        method_get: typing.Union['StructuresStatisticSeriesData', schemas.Unset] = schemas.unset,
        method_post: typing.Union['StructuresStatisticSeriesData', schemas.Unset] = schemas.unset,
        method_put: typing.Union['StructuresStatisticSeriesData', schemas.Unset] = schemas.unset,
        method_head: typing.Union['StructuresStatisticSeriesData', schemas.Unset] = schemas.unset,
        method_delete: typing.Union['StructuresStatisticSeriesData', schemas.Unset] = schemas.unset,
        method_options: typing.Union['StructuresStatisticSeriesData', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'S3StatisticGetRequestResponse':
        return super().__new__(
            cls,
            *args,
            method_get=method_get,
            method_post=method_post,
            method_put=method_put,
            method_head=method_head,
            method_delete=method_delete,
            method_options=method_options,
            _configuration=_configuration,
            **kwargs,
        )

from beget_openapi_cloud.model.structures_statistic_series_data import StructuresStatisticSeriesData
