# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.4.1
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_cloud import schemas  # noqa: F401


class S3S3Configuration(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            subscription_disk_size = schemas.IntSchema
            price_overload_day = schemas.Float64Schema
            price_overload_month = schemas.Float64Schema
            __annotations__ = {
                "subscription_disk_size": subscription_disk_size,
                "price_overload_day": price_overload_day,
                "price_overload_month": price_overload_month,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["subscription_disk_size"]) -> MetaOapg.properties.subscription_disk_size: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["price_overload_day"]) -> MetaOapg.properties.price_overload_day: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["price_overload_month"]) -> MetaOapg.properties.price_overload_month: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["subscription_disk_size", "price_overload_day", "price_overload_month", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["subscription_disk_size"]) -> typing.Union[MetaOapg.properties.subscription_disk_size, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["price_overload_day"]) -> typing.Union[MetaOapg.properties.price_overload_day, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["price_overload_month"]) -> typing.Union[MetaOapg.properties.price_overload_month, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["subscription_disk_size", "price_overload_day", "price_overload_month", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        subscription_disk_size: typing.Union[MetaOapg.properties.subscription_disk_size, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        price_overload_day: typing.Union[MetaOapg.properties.price_overload_day, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        price_overload_month: typing.Union[MetaOapg.properties.price_overload_month, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'S3S3Configuration':
        return super().__new__(
            cls,
            *args,
            subscription_disk_size=subscription_disk_size,
            price_overload_day=price_overload_day,
            price_overload_month=price_overload_month,
            _configuration=_configuration,
            **kwargs,
        )
