# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_cloud import schemas  # noqa: F401


class S3S3Configuration(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            free_traffic_amount = schemas.IntSchema
            traffic_price_day = schemas.Float64Schema
            traffic_price_month = schemas.Float64Schema
            __annotations__ = {
                "free_traffic_amount": free_traffic_amount,
                "traffic_price_day": traffic_price_day,
                "traffic_price_month": traffic_price_month,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["free_traffic_amount"]) -> MetaOapg.properties.free_traffic_amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["traffic_price_day"]) -> MetaOapg.properties.traffic_price_day: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["traffic_price_month"]) -> MetaOapg.properties.traffic_price_month: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["free_traffic_amount", "traffic_price_day", "traffic_price_month", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["free_traffic_amount"]) -> typing.Union[MetaOapg.properties.free_traffic_amount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["traffic_price_day"]) -> typing.Union[MetaOapg.properties.traffic_price_day, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["traffic_price_month"]) -> typing.Union[MetaOapg.properties.traffic_price_month, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["free_traffic_amount", "traffic_price_day", "traffic_price_month", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        free_traffic_amount: typing.Union[MetaOapg.properties.free_traffic_amount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        traffic_price_day: typing.Union[MetaOapg.properties.traffic_price_day, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        traffic_price_month: typing.Union[MetaOapg.properties.traffic_price_month, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'S3S3Configuration':
        return super().__new__(
            cls,
            *args,
            free_traffic_amount=free_traffic_amount,
            traffic_price_day=traffic_price_day,
            traffic_price_month=traffic_price_month,
            _configuration=_configuration,
            **kwargs,
        )
