# coding: utf-8

"""
    API Управляемых сервисов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.4.2
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_cloud import schemas  # noqa: F401


class StructuresAddressInfo(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            
            
            class public(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['StructuresAddressInfoPublicAddress']:
                        return StructuresAddressInfoPublicAddress
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['StructuresAddressInfoPublicAddress'], typing.List['StructuresAddressInfoPublicAddress']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'public':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'StructuresAddressInfoPublicAddress':
                    return super().__getitem__(i)
            
            
            class private(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['StructuresAddressInfoPrivateAddress']:
                        return StructuresAddressInfoPrivateAddress
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['StructuresAddressInfoPrivateAddress'], typing.List['StructuresAddressInfoPrivateAddress']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'private':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'StructuresAddressInfoPrivateAddress':
                    return super().__getitem__(i)
            __annotations__ = {
                "public": public,
                "private": private,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["public"]) -> MetaOapg.properties.public: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["private"]) -> MetaOapg.properties.private: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["public", "private", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["public"]) -> typing.Union[MetaOapg.properties.public, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["private"]) -> typing.Union[MetaOapg.properties.private, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["public", "private", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        public: typing.Union[MetaOapg.properties.public, list, tuple, schemas.Unset] = schemas.unset,
        private: typing.Union[MetaOapg.properties.private, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'StructuresAddressInfo':
        return super().__new__(
            cls,
            *args,
            public=public,
            private=private,
            _configuration=_configuration,
            **kwargs,
        )

from beget_openapi_cloud.model.structures_address_info_private_address import StructuresAddressInfoPrivateAddress
from beget_openapi_cloud.model.structures_address_info_public_address import StructuresAddressInfoPublicAddress
